### ISSUE TITLE
How are Boxes containing deleted products displayed?

### ISSUE THREAD

**Issue by HaGuesto** [dropapp/dropapp#109]
If you delete a product and there is still a box in the database which is referring to that product, an error is thrown when you open Find a box

**Comment by bfirsh** [comment]
@barto74 Made a good point that we should probably be using delete flags. This will probably make this case easier.

A few options:

1) we leave it pointing at the deleted product
2) we delete the boxes (with confirmation!)
3) we offer the option to move the boxes to another product

**Comment by barto74** [comment]
Also to be able to review orders, transactions, stocks, etc in the past, we always need delete flags for everything. I think we should define a delete policy for every kind of deletable item. It might not be the same everywhere. 

- For boxes: no reason to assume that those boxes will disappear upon deleting a product, so option 2 is not valid. Option 1: the result is that there are still boxes around with that deleted product, but making new boxes is not possible. Option 3: we assume that the deleted product will be replaced by another similar one, is that the case?
- For users: deleted mean that existing stuff always refer to that user as the creator/modifier/etc
- For categories: maybe only deletable if the user makes the category empty.
- For orders: maybe these are only cancellable, never deletable.
