### ISSUE TITLE
Add some helper text to explain what product names should be 

### ISSUE THREAD

**Issue by bfirsh** [dropapp/dropapp#123]
T-Shirts in a Man category should have the name "T-Shirts" not "Men's T-Shirts"

**Comment by barto74** [comment]
I tried to do it, but an helpertext seems only to be allowed in a TextField and not in Field

**Comment by bfirsh** [comment]
@barto74 hmmm... I'll have a look. What was the copy you used exactly? (So I don't have to invent something ;)

**Comment by barto74** [comment]
Enter a name, like 'T-Shirt' or 'Socks'. Don't reuse the category name here.
