### ISSUE TITLE
Make a box

### ISSUE THREAD

**Issue by bfirsh** [dropapp/dropapp#18]
## Summary

Create a box full of products ready to be put in the warehouse. Typically done as part of a sorting process.

## User stories

...

## Related issues

...

**Comment by barto74** [comment]
A live wireframe for this is here: https://xd.adobe.com/view/e4e85f42-4d6c-4d70-4a81-fd33d230dce8-92d9/
<img width="1296" alt="screen shot 2018-05-29 at 18 37 07" src="https://user-images.githubusercontent.com/38283578/40669323-594f8146-636f-11e8-90f0-d77979362921.png">
Comments welcome @bfirsh @HaGuesto

**Comment by HaGuesto** [comment]
@barto74 We could change the selection of a product to the same way as in the ordering process. It would create one or two frames more, but in the end the selection of the product would come with less errors. We can guide the volunteers better to choose the right product.

**Comment by bfirsh** [comment]
@barto74 A couple of comments: 

1) Have you thought about how the flow would work if you aren't using a QR code? Could just be a button on the scanner page saying "This box does not have a QR code".
2) Is there a reason the QR code scanning is before entering the details? It seems to flow better if you enter the details first, but I can't rationalise why.

**Comment by barto74** [comment]
@bfirsh:
1: there should be a manual override, indeed. Will add.
2: in my experience, the flow is: you take a label, you scan it, you start writing on it and filling in the form and you stick it to the box. The other way around would also be possible, for sure. For me it feels a bit indifferent.

**Comment by barto74** [comment]
we decided to not make a manual override... we want people to stick to the process.
in the future we might want to fully disable qr usage on organization level if there is a need for it.

**Comment by bfirsh** [comment]
This is pretty much done. A few other little bits which we will record separately.
