### ISSUE TITLE
Find a box

### ISSUE THREAD

**Issue by bfirsh** [dropapp/dropapp#20]
## Summary
...

## User stories
...

## Wireframes
Second version (check the clickable version [here](https://xd.adobe.com/view/e4e85f42-4d6c-4d70-4a81-fd33d230dce8-92d9/))
- You can manually only select status: available, reserved (for internal) and lost. Other statuses only through making and processing orders.
- Filter button filters statuses and by default only show available boxes.
- Edit screen is made - we should let this part of the wireframe keep aligned with #18 

<img width="1133" alt="40727520-b9285338-6430-11e8-87b1-de9872032948" src="https://user-images.githubusercontent.com/40906/40729519-38d29e82-6435-11e8-954b-0be782aec940.png">

(from https://github.com/dropapp/dropapp/issues/47 )

**Comment by barto74** [comment]
@HaGuesto try to use the live demo, it gives you more of a feel than watching the graphic. 3 and 5 are quite fast steps and as i see required to give some feedback about what you did and where you go.
frame 4: you would be able to select all products (in which also the 'All' option could be available) and then you get all boxes. Which is actually in the old app the default view, but that is quite a long list that you not always use.
Frame 7-9: see frame 10, you can filter on status, by default you only see the available boxes but you might want to see others.
frame 11: you only change status into lost or not available, you don't change into ordered/picked/delivered. And this may or may not be a user rights question - but we don't have user rights atm.

**Comment by bfirsh** [comment]
<img width="1146" alt="screen shot 2018-06-01 at 12 35 35" src="https://user-images.githubusercontent.com/40906/40835556-6f6cb3c0-659c-11e8-8e56-0239285f5ae3.png">

New wireframe from @barto74 on Slack.
