### ISSUE TITLE
Decide on a name

### ISSUE THREAD

**Issue by bfirsh** [dropapp/dropapp#26]
Current ideas revolving around "Box"...

BoxShop
BoxHouse
BoxHub
BoxAid
DropBox (oh wait)
Box Box Box

**Comment by bfirsh** [comment]
Boxwork

**Comment by bfirsh** [comment]
Boxwise

**Comment by bfirsh** [comment]
Betterbox

**Comment by bfirsh** [comment]
Boxcode

**Comment by bfirsh** [comment]
Boxfarm
Rightbox

**Comment by bfirsh** [comment]
Boxpack

**Comment by bfirsh** [comment]
Unbox

**Comment by bfirsh** [comment]
Boxcloud (oh dear)

**Comment by bfirsh** [comment]
BoxedIn

**Comment by bfirsh** [comment]
Robox
Boxbot

**Comment by bfirsh** [comment]
Boxitive

**Comment by barto74** [comment]
Box in other languages that i found more or less appealing:
Boks Sunduq (in arabic) Baksa Caixa Scatula Skatolo Kasti Carton Dibba Doboz Bosca Arca Kaxxa Eske Cutie Kutu 

The word **Carton** works in many languages and sounds quite friendly
**Dobox** is nice as it is active (Doboz is hungarian)

**Comment by bfirsh** [comment]
@barto74 @HaGuesto I think we can safely say we've done this, right? ;)
