### ISSUE TITLE
Make a wireframe for the onboarding

### ISSUE THREAD

**Issue by barto74** [dropapp/dropapp#31]

**Comment by barto74** [comment]
See the first draft of the wireframe here. Please comment @bfirsh @HaGuesto 
<img width="1126" alt="screen shot 2018-05-29 at 12 10 34" src="https://user-images.githubusercontent.com/38283578/40649416-89701704-6339-11e8-86e1-f44c7f87ad5d.png">

**Comment by bfirsh** [comment]
succeeded by #48
