### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by bfirsh** [dropapp/dropapp#38]
Google Analytics is probably good starting point.

**Comment by HaGuesto** [comment]
@bfirsh What do you mean by Analytics?
Do mean the overview of how many items are stored for each product or something else?

**Comment by bfirsh** [comment]
@HaGuesto Product analytics. At the very least, something like Google Analytics to see if the product is being used. Sometime down the line where we want to actually get data about how the product is being used, we could use something like Mixpanel.
