### ISSUE TITLE
Creation of QR-code labels

### ISSUE THREAD

**Issue by barto74** [dropapp/dropapp#41]

**Comment by barto74** [comment]
The old dropapp relies on the QR API at qrserver.com. Is that the best solution?

**Comment by bfirsh** [comment]
@barto74 We can probably generate them ourselves pretty easily. I'd also like to have a discussion about:

1) Making sure they are secure
2) Making them smaller so they scan more reliably. (e.g. by using a link shortener)

**Comment by barto74** [comment]
If we use the QR-codes only from within the app, we don't need to include a full URL. A reference to the type of code ('box', 'order form', etc) and the id, packed into a hash should then be enough. That is more secure, i think. 
We only need the API at the moment we create new QR's, so it is not so critical to work offline. No problems with the API have been reported since nov '17, so I would at least propose to use it in the early versions of our project.

**Comment by barto74** [comment]
Actually Google has a nice API to make QR codes. Maybe more safe as you never know when a small third party takes an API down. And another benefit: they allow to make slightly bigger codes, with better error correction, which is very beneficial when labels get damaged.
https://developers.google.com/chart/infographics/docs/qr_codes

**Comment by barto74** [comment]
Labels are best made as PDF-files. It's rather easy to make sure that elements are exactly printed on the position where we want them. Experiments with HTML went miserable, lots of differences between browsers and depending on proper user configuration.
It seems that http://pdfkit.org would be a good library to make PDF's in our setup, but i'm curious @bfirsh what you think.
It's something that I could probably code quite easily.

**Comment by barto74** [comment]
The procedure as I see it:
To print a batch of QR-codes for boxes, we ask the user how many they want. We generate a bit of random data and create a PDF with all the labels. We might even not have to save that data in a table (as the old dropapp), but just after reading the QR-code for a new box, save that piece of data as an attribute of the box document in firebase. The only reason to save the generated codes, is to prevent duplicates, but i think that is statistically negligible.
For the order list, it might make sense to generate the QR from the identifier in Firebase?
