### ISSUE TITLE
Onboarding flow

### ISSUE THREAD

**Issue by bfirsh** [dropapp/dropapp#48]
We need to on board users in two ways:

* Sign up and create an organisation
* Sign and join an organisation via an invite

## Wireframe

From @barto74 (#31):

<img width="1126" alt="40649416-89701704-6339-11e8-86e1-f44c7f87ad5d" src="https://user-images.githubusercontent.com/40906/40707210-aeaafb1e-63f8-11e8-9a32-37b9e732cad3.png">

## Implementation

We somehow need to create user profiles with an organization in a way that they cannot set the organization themselves. Maybe this needs to be a cloud function?

**Comment by HaGuesto** [comment]
@barto74 I would formulate the Slack invite a bit different. We should discuss what the role of slack should be. For example only for support...

**Comment by barto74** [comment]
@HaGuesto feel free to contribute to the formulation. I think Slack is definitely for support, feature requests. 
And about the roles: yes, in the future for sure, but the roles are not in the MVP.

**Comment by bfirsh** [comment]
This looks great to me.

A little thing: I would agree with @HaGuesto that the Slack invite at that stage doesn't work. It looks like that is the call to action. Getting users onto Slack could be something we do later, after they have started using the app.

**Comment by barto74** [comment]
I agree to delete it, see the updated wireframe
