### ISSUE TITLE
Add hook to remind you to install dependencies/deploy stuff to firebase

### ISSUE THREAD

**Issue by bfirsh** [dropapp/dropapp#77]
Like this: https://github.com/frontsideair/yarnhook

It could also check to see if firestore.rules has changed, and remind you to deploy. Probably not best to do that automatically because you mind be pointing at the production environment or something. 😬

**Comment by meetall** [comment]
Hello, I've created a [pull request](https://github.com/dropapp/dropapp/pull/139)  for this. Could you please have a look?

**Comment by bfirsh** [comment]
Thanks @meetall! ✨
